apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/datalogger-net: "true"
        io.kompose.service: admin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: tracycardenas@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "1234567890"
            - name: TZ
              value: America/Guayaquil
          image: dpage/_admin4
          name: admin
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
