version: '3.6'

services:
  srvdb:
    image: postgres
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: tracy
      POSTGRES_DB: libreria
      POSTGRES_PASSWORD: 12345
      TZ:  America/Guayaquil
    ports:
      - 5432:5432
    networks:
      - datalogger_net
    volumes: 
      - db:/var/lib/postgresql/data
     
    

  srvwildfly:
    image: ups/demoapp
    container_name: srvwildfly
    hostname: srvwildfly
    environment:
      TZ:  America/Guayaquil
    ports:
      - 8080:8080 #puertoPC : puertoContenedor
      - 8009:8009
      - 9990:9990
      - 8787:8787
    #command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -c standalone.xml -bmanagement 0.0.0.0 --debug *:8787
    depends_on:
      - srvdb
    networks:
      - datalogger_net
  
volumes:
  db:
    driver: local  
      
networks:
  datalogger_net:
