apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: srvwildfly
  name: srvwildfly
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: srvwildfly
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/datalogger-net: "true"
        io.kompose.service: srvwildfly
    spec:
      containers:
        - env:
            - name: TZ
              value: America/Guayaquil
          image: tracycardenas/demoapp
          name: srvwildfly
          ports:
            - containerPort: 8080
            - containerPort: 8009
            - containerPort: 9990
            - containerPort: 8787
          resources: {}
      hostname: srvwildfly
      restartPolicy: Always
status: {}
