apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: swaggereditor
  name: swaggereditor
spec:
  ports:
    - name: "9999"
      port: 9999
      targetPort: 8080
  selector:
    io.kompose.service: swaggereditor
status:
  loadBalancer: {}
